# Site settings
title: "mJay Kwon Resume"
description: "Hi! Good to see you"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "mJay Kwon"
resume_title:                   "Java Senior Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "audwnddl@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+82-10-9183-8260"
resume_contact_address:         "Suji-gu, Yongin-si, Gyeonggi-do, Republic of Korea"

resume_header_contact_info:     "Suji-gu, Yongin-si, Gyeonggi-do, Republic of Korea • +82-10-9183-8260 • audwnddl@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>JAVA Senior 개발자입니다. 차세대를 비롯한 다양한 프로젝트 수행 경험, 안정적인 시스템 운영, 금융분야에서 10년이상 분석설계, 프로젝트 리딩 및 빠른 Trouble Shooting, JAVA, ProFrame, MDD, Spring, Springboot, 전자정부프레임워크, 보험, 영업지원, 신계약, 차세대수행, 아키텍트, 분석설계, Backend 개발</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       false
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
#  resume_github_url:            "https://github.com/jglovier/resume-template"
#  resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
#  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
#  resume_website_url:           "http://joelglovier.com"
#  resume_medium_url:            "https://medium.com/@jglovier"
#resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
